### ISSUE TITLE
Support labeled wikilinks

### ISSUE THREAD

**Issue by padamson** [wikibonsai/wikirefs#3]
Often, when including a `[[wikilink]]` it would be useful for preview mode to show different text besides the file name or the title. A possible solution would be to add a `wikilabel` to the syntax:

 'wikitext'
      👇
  • <-------------> •
[[wikilabel | wikilink]]
• <---------------> •
          👆
      'wikistring'

      'wikitext'
    👇          👇
 • <-> •    • <-------------> •
:reftype::[[wikilabel | wikilink]]
• <-------------------------> •
             👆
           'wikistring'

Then preview mode would display `wikilabel`, if present, or the `title` of `wikilink` if `wikilabel` is not present.

**Comment by manunamz** [comment]
Labels are already supported for wikilinks. The source of confusion may be the fact that labels are expected on the **right** side of the pipe:

```markdown
[[wikilink|wikilabel]]
:reftype::[[wikilink|wikilabel]]
```

You can see some of the passing tests here:

Untyped: https://github.com/wikibonsai/wikirefs/blob/main/spec/cases/wikilink-untyped.ts#L95
Typed: https://github.com/wikibonsai/wikirefs/blob/main/spec/cases/wikilink-typed.ts#L118

Among apps and tools that support the `[[wikilink]]`, there is definitely a split between left-side v right-side label text. In my experience, right-side seemed to be (slightly?) more prevalent across the ecosystem, so that is what is defined and supported here.

**Comment by padamson** [comment]
thanks, sorry I missed that. and thanks for creating and sharing wikibonsai
